name: Build & Push Docker Image to ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NAME: myapp
  AWS_REGION: ap-south-1

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build & Push SageMaker Torch image
        run: |
          make sagemaker-torch \
            AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }} \
            AWS_REGION=${{ env.AWS_REGION }} \
            ECR_REPO=${{ secrets.ECR_REPO_TORCH }} \
            ECR_PUSH=true \
            NAME=${{ env.NAME }}

      - name: Build & Push SageMaker TF image
        run: |
          make sagemaker-tf \
            AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }} \
            AWS_REGION=${{ env.AWS_REGION }} \
            ECR_REPO=${{ secrets.ECR_REPO_TF }} \
            ECR_PUSH=true \
            NAME=${{ env.NAME }}
